In this features the about and index page are finished
Dagic-zewdu/Capstone-project-1 pull request #1
Opened 2022-02-03 19:55 UTC by Dagic-zewdu

- Created index.html file which server as the landing page of this project

2022-02-03 22:15 UTC, brytebee requested changes
Hi, @Dagic-zewdu 👋, 

## Highlights
Good job so far!
- good video description👏
- excellent commit messages👏
- no linter errors👏
- the app is deployed using GitHub pages👏

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-03 22:15 UTC, brytebee commented on index.html
> +            </ul>
- [ ] **Required:** You have done an amazing job deploying your app using GitHub pages👏. However, you haven't accurately set up your links.
You should have a link to the `Home` page that navigates users back to the Home page when they are on the `About` page.

- [ ] **Required:** The above should be implemented for both screens. (Desktop & Mobile)

2022-02-03 22:15 UTC, brytebee commented on index.html
> +    </footer>
- [ ] **Required:** Your footer looks really good, however, we can make some changes to make it look more similar to the Template.
- Your footer should maintain the margin of the middle section
- Kindly add the copyright to the other footer text.
- consider separating the footer and the combined text with some padding. 

Your Design | Behance Template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/152430205-39adcddd-a2c2-4f48-8161-3bc639e49149.png) | ![image](https://user-images.githubusercontent.com/27709832/152430273-edcf83b8-e92e-4569-ae7b-ca1b1c10882a.png)

2022-02-03 22:15 UTC, brytebee commented on about.html
> +    </footer>
- [ ] **Required:** On this `About` page, the footer is required to have a dark background.

![image](https://user-images.githubusercontent.com/27709832/152431649-60ed5729-3e4c-434e-8c6c-70bb6962d9b8.png)

2022-02-03 22:15 UTC, brytebee commented on index.html
> +    </section>
- [ ] **Required:** Consider making the following changes to the top section
- Fix all console errors.
![image](https://user-images.githubusercontent.com/27709832/152433408-50df0c00-5895-4d82-991a-ea6ddf2c992f.png)

- [ ] You have correctly aligned all elements 👏. However, consider the following changes to have a similar design to the Template.

1. The should be a size difference between you `h1` and `h2`.
2. The `h1` text should have a background image. The `font-family: cocogoose`  as pointed out above is not loaded.
3. The font-weight makes it difficult to read, it is therefore not good for UX. 
4. The appropriate `font-family` and `font-weight` should be applied.

Your Design | Template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/152435072-38fe3253-c98d-4f62-9663-08de45b14de1.png) | ![image](https://user-images.githubusercontent.com/27709832/152435145-34dc30fd-7c93-487f-b995-c9f81e416881.png)

2022-02-03 22:15 UTC, brytebee commented on about.html
> +    </section>
- [ ] **Required:** Kindly fix the console errors on this page as well.

![image](https://user-images.githubusercontent.com/27709832/152436173-5fabd34b-4624-4743-8334-bb8356b9178c.png)

- [ ] **Required:** To have a similar design, consider the following:

1. The gap (padding/margin) given between the top of the page and the header is too big.
2. Use appropriate `font-family` and `font-weight`. Align the header to the centre on all screens of the `About` page.
3. The text isn't visible.
4. The mail is **_underlined_** and has a small arrowhead icon.

Your Design | Template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/152437445-242d9033-f712-4f52-b627-4a070ca5f872.png) | ![image](https://user-images.githubusercontent.com/27709832/152437525-aaa6f951-caf7-4586-b9b3-f6c28b597b5e.png)

2022-02-04 10:16 UTC, ReshyResh requested changes
# Hi @Dagic-zewdu , 

### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] Please make sure that, as the previous reviewer requested, the footer matches the given template. The layout should be divided into two sections, with the logo on the left and the text on the right. Currently, you have the sections stacked on top of each other.
Also, please change the footer on the about page to have a dark background, as requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 10:56 UTC, Dagic-zewdu commented
The about page dark footer is not necessary(not described on the template) and my previous commenter doesn't give me suggestions on that so will stick to the white background footer.

2022-02-04 10:58 UTC, ReshyResh commented on about.html
> +    </footer>
@Dagic-zewdu you can see the previous reviewer requested the change of the background here.

2022-02-04 11:00 UTC, ReshyResh commented
@Dagic-zewdu  is it s requirement from the template, if you open it you'll see that the background of the footer changes.


| Homepage footer  | About page footer |
| ------------- | ------------- |
| ![](https://i.imgur.com/sGoELG7.png)  |  ![](https://i.imgur.com/I8kLm8F.png) |

2022-02-04 11:07 UTC, Dagic-zewdu commented
Okay thanks i will work on that

2022-02-04 11:16 UTC, ReshyResh approved these changes
# Hi again, @Dagic-zewdu , 

### Good job addressing the changes requested previously.
#### Your capstone project is complete and it looks amazing!  There is nothing else to say other than... it's time to merge it!
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-04 12:05 UTC, merged